### ISSUE TITLE
Upgrade CORAL to use mysqli instead of deprecated mysql

### ISSUE THREAD

**Issue by remocrevo** [ndlibersa/resources#36]
This warning is included on all php.net documentation about mysql functions:

"This extension is deprecated as of PHP 5.5.0, and will be removed in the future. Instead, the MySQLi or PDO_MySQL extension should be used. See also "MySQL: choosing an API" guide and related FAQ for more information."

**Comment by benheet** [comment]
how much of an effort will this be?

**Comment by remocrevo** [comment]
The initial conversion of the code could be quick (there is even a [utility to help with it](https://github.com/philip/MySQLConverterTool)), but it would require thorough testing. If a few people could commit to helping, and if someone could guide the testing to make sure all significant database functions were tested, it could move fairly quickly.

**Comment by PaulPoulain** [comment]
Le 13/04/2015 14:26, remocrevo a écrit :
>
> The initial conversion of the code could be quick (there is even a 
> utility to help with it 
> <https://github.com/philip/MySQLConverterTool>), but it would require 
> thorough testing. If a few people could commit to helping, and if 
> someone could guide the testing to make sure all significant database 
> functions were tested, it could move fairly quickly.
>
>

And here, the words "unit tests" and "jenkins" come to my mind (but this 
is NOT a quick & easy goal. But a worth one ;-) )

-- 
Paul Poulain, Associé-gérant / co-owner
BibLibre, expert du logiciel libre pour les bibliothèques
BibLibre, Open Source software for libraries expert

**Comment by jeffnm** [comment]
I have some programmer hours available this summer that could tackle the mysql to mysqli conversion, but as was mentioned previously, testing is going to be time consuming. Are there any objections to my team making the mysqli updates and putting them on a new branch for testing?

**Comment by remocrevo** [comment]
Sounds good, @jeffnm. Thanks for working on this.

**Comment by coraladmin** [comment]
@jeffnm how is this effort going?

**Comment by jeffnm** [comment]
The changes have been made and the pull requests came in from Derek. I
think it would be wise if one other institution installed and tested them
just to make sure that they are working as expected. If I can get one other
institution to test each of the modules and comment to that effect, I'll go
ahead and merge them.

**Comment by remocrevo** [comment]
Fixed by pull request #48

**Comment by remocrevo** [comment]
I was wrong. Pull request #48 was closed because it contains errors and needs to be redone. This issue should remain open until a new pull request is merged to fix the problem.

**Comment by jeffnm** [comment]
https://github.com/ndlibersa/resources/pull/55 was merged to fix this.
