### ISSUE TITLE
Column missing in table when installing resources module

### ISSUE THREAD

**Issue by rivanov2** [ndlibersa/resources#41]
My apologies if this is not the correct place to post this issue, but I cannot find any references in the documentation for this type of error, or any other online outlet to post to. This is my first time attempting to install CORAL.

The following errors occurred:
Key column 'isbnOrISSN' doesn't exist in table

For statement: ALTER TABLE `coral_resources_prod`.`Resource` ADD INDEX `Index_createDate`(`createDate`), ADD INDEX `Index_createLoginID`(`createLoginID`), ADD INDEX `Index_titleText`(`titleText`), ADD INDEX `Index_isbnOrISSN`(`isbnOrISSN`), ADD INDEX `Index_statusID`(`statusID`), ADD INDEX `Index_resourceTypeID`(`resourceTypeID`), ADD INDEX `Index_resourceFormatID`(`resourceFormatID`), ADD INDEX `Index_acquisitionTypeID`(`authenticationTypeID`), ADD INDEX `catalogingTypeID` ( `catalogingTypeID` ), ADD INDEX `catalogingStatusID` ( `catalogingStatusID` ), ADD INDEX `Index_All`(`createDate`, `createLoginID`, `titleText`, `isbnOrISSN`, `statusID`, `resourceTypeID`, `resourceFormatID`, `acquisitionTypeID`)

**Comment by remocrevo** [comment]
Hi,

This is the right place to post this issue. Thank you for telling us about this.  It has just been fixed by pull request #39 , so please try installing again from the beginning and let us know if you have trouble.
