### ISSUE TITLE
Missing label text in New Resource form

### ISSUE THREAD

**Issue by sjlevy** [ndlibersa/resources#72]
An echo needs to be added to line 131 of ajax_forms/getNewResourceForm.php

Original Line:
`<span class='surroundBoxTitle'>&nbsp;&nbsp;<label for='resourceFormatID'><b><?php _("Format");?></b></label>&nbsp;<span class='bigDarkRedText'>*</span>&nbsp;&nbsp;</span>`

Fixed Line:
`<span class='surroundBoxTitle'>&nbsp;&nbsp;<label for='resourceFormatID'><b><?php echo _("Format");?></b></label>&nbsp;<span class='bigDarkRedText'>*</span>&nbsp;&nbsp;</span>`

**Comment by sjlevy** [comment]
Nevermind it looks like this was fixed in the new repository:

https://github.com/Coral-erm/Coral/blob/master/resources/ajax_forms/getNewResourceForm.php

**Comment by bdroubay** [comment]
That was already fixed and merged — I probably caught it with all of the translation updates, which are currently being reviewed for context.

**Comment by bdroubay** [comment]
I will fix that now and merge.

Thanks!
